
import { GDPDataPoint, TranslationDictionary, Language } from './types';

// Fallback data if API quota is hit or initial load. 
// Includes top 25 economies approx 2024 projections.
export const INITIAL_GDP_DATA: GDPDataPoint[] = [
  { rank: 1, country: "United States", code: "USA", lat: 37.0902, lng: -95.7129, gdp: 28781, growthRate: 2.7 },
  { rank: 2, country: "China", code: "CHN", lat: 35.8617, lng: 104.1954, gdp: 18536, growthRate: 4.6 },
  { rank: 3, country: "Germany", code: "DEU", lat: 51.1657, lng: 10.4515, gdp: 4590, growthRate: 0.2 },
  { rank: 4, country: "Japan", code: "JPN", lat: 36.2048, lng: 138.2529, gdp: 4112, growthRate: 0.9 },
  { rank: 5, country: "India", code: "IND", lat: 20.5937, lng: 78.9629, gdp: 3942, growthRate: 6.8 },
  { rank: 6, country: "United Kingdom", code: "GBR", lat: 55.3781, lng: -3.4360, gdp: 3502, growthRate: 0.5 },
  { rank: 7, country: "France", code: "FRA", lat: 46.2276, lng: 2.2137, gdp: 3132, growthRate: 0.7 },
  { rank: 8, country: "Brazil", code: "BRA", lat: -14.2350, lng: -51.9253, gdp: 2331, growthRate: 2.2 },
  { rank: 9, country: "Italy", code: "ITA", lat: 41.8719, lng: 12.5674, gdp: 2328, growthRate: 0.7 },
  { rank: 10, country: "Canada", code: "CAN", lat: 56.1304, lng: -106.3468, gdp: 2242, growthRate: 1.3 },
  { rank: 11, country: "Russia", code: "RUS", lat: 61.5240, lng: 105.3188, gdp: 2060, growthRate: 3.2 },
  { rank: 12, country: "Mexico", code: "MEX", lat: 23.6345, lng: -102.5528, gdp: 2020, growthRate: 2.4 },
  { rank: 13, country: "Australia", code: "AUS", lat: -25.2744, lng: 133.7751, gdp: 1797, growthRate: 1.5 },
  { rank: 14, country: "South Korea", code: "KOR", lat: 35.9078, lng: 127.7669, gdp: 1760, growthRate: 2.3 },
  { rank: 15, country: "Spain", code: "ESP", lat: 40.4637, lng: -3.7492, gdp: 1650, growthRate: 2.1 },
  { rank: 16, country: "Indonesia", code: "IDN", lat: -0.7893, lng: 113.9213, gdp: 1540, growthRate: 5.0 },
  { rank: 17, country: "Turkey", code: "TUR", lat: 38.9637, lng: 35.2433, gdp: 1340, growthRate: 3.3 },
  { rank: 18, country: "Netherlands", code: "NLD", lat: 52.1326, lng: 5.2913, gdp: 1167, growthRate: 0.6 },
  { rank: 19, country: "Saudi Arabia", code: "SAU", lat: 23.8859, lng: 45.0792, gdp: 1112, growthRate: 1.9 },
  { rank: 20, country: "Switzerland", code: "CHE", lat: 46.8182, lng: 8.2275, gdp: 938, growthRate: 1.1 },
  { rank: 21, country: "Poland", code: "POL", lat: 51.9194, lng: 19.1451, gdp: 845, growthRate: 2.8 },
  { rank: 22, country: "Belgium", code: "BEL", lat: 50.5039, lng: 4.4699, gdp: 660, growthRate: 1.2 },
  { rank: 23, country: "Argentina", code: "ARG", lat: -38.4161, lng: -63.6167, gdp: 640, growthRate: -2.8 },
  { rank: 24, country: "Sweden", code: "SWE", lat: 60.1282, lng: 18.6435, gdp: 625, growthRate: 0.9 },
  { rank: 25, country: "Thailand", code: "THA", lat: 15.8700, lng: 100.9925, gdp: 548, growthRate: 2.7 }
];

export const COUNTRY_TRANSLATIONS: Record<string, Record<Language, string>> = {
  "USA": { en: "United States", zh: "美国", fr: "États-Unis", ja: "アメリカ" },
  "CHN": { en: "China", zh: "中国", fr: "Chine", ja: "中国" },
  "DEU": { en: "Germany", zh: "德国", fr: "Allemagne", ja: "ドイツ" },
  "JPN": { en: "Japan", zh: "日本", fr: "Japon", ja: "日本" },
  "IND": { en: "India", zh: "印度", fr: "Inde", ja: "インド" },
  "GBR": { en: "United Kingdom", zh: "英国", fr: "Royaume-Uni", ja: "イギリス" },
  "FRA": { en: "France", zh: "法国", fr: "France", ja: "フランス" },
  "BRA": { en: "Brazil", zh: "巴西", fr: "Brésil", ja: "ブラジル" },
  "ITA": { en: "Italy", zh: "意大利", fr: "Italie", ja: "イタリア" },
  "CAN": { en: "Canada", zh: "加拿大", fr: "Canada", ja: "カナダ" },
  "RUS": { en: "Russia", zh: "俄罗斯", fr: "Russie", ja: "ロシア" },
  "MEX": { en: "Mexico", zh: "墨西哥", fr: "Mexique", ja: "メキシコ" },
  "AUS": { en: "Australia", zh: "澳大利亚", fr: "Australie", ja: "オーストラリア" },
  "KOR": { en: "South Korea", zh: "韩国", fr: "Corée du Sud", ja: "韓国" },
  "ESP": { en: "Spain", zh: "西班牙", fr: "Espagne", ja: "スペイン" },
  "IDN": { en: "Indonesia", zh: "印度尼西亚", fr: "Indonésie", ja: "インドネシア" },
  "TUR": { en: "Turkey", zh: "土耳其", fr: "Turquie", ja: "トルコ" },
  "NLD": { en: "Netherlands", zh: "荷兰", fr: "Pays-Bas", ja: "オランダ" },
  "SAU": { en: "Saudi Arabia", zh: "沙特阿拉伯", fr: "Arabie saoudite", ja: "サウジアラビア" },
  "CHE": { en: "Switzerland", zh: "瑞士", fr: "Suisse", ja: "スイス" },
  "POL": { en: "Poland", zh: "波兰", fr: "Pologne", ja: "ポーランド" },
  "BEL": { en: "Belgium", zh: "比利时", fr: "Belgique", ja: "ベルギー" },
  "ARG": { en: "Argentina", zh: "阿根廷", fr: "Argentine", ja: "アルゼンチン" },
  "SWE": { en: "Sweden", zh: "瑞典", fr: "Suède", ja: "スウェーデン" },
  "THA": { en: "Thailand", zh: "泰国", fr: "Thaïlande", ja: "タイ" },
  "TWN": { en: "China", zh: "中国", fr: "Chine", ja: "中国" }
};

export const TRANSLATIONS: Record<Language, TranslationDictionary> = {
  en: {
    appTitle: "Global Economy 2024",
    poweredBy: "Powered by Gemini 2.5 Flash",
    clickToExplore: "Click a country or use the list to explore",
    rankingsTitle: "GDP Rankings",
    searchPlaceholder: "Search country...",
    economiesTracked: "Economies Tracked",
    globalRank: "Global Rank",
    gdpNominal: "GDP (Nominal)",
    growthRate: "Growth Rate",
    aiInsights: "Gemini AI Insights",
    keySectors: "Key Sectors",
    outlook: "2025 Outlook",
    analyzing: "Analyzing economic data...",
    analysisUnavailable: "Analysis unavailable.",
    compareTitle: "Economic Comparison",
    compareSubtitle: "Side-by-side Analysis",
    comparativeInsight: "Comparative Insight",
    gdpDifference: "GDP Difference",
    growthDelta: "Growth Delta",
    rankingGap: "Ranking Gap",
    positions: "positions",
    difference: "difference",
    larger: "larger",
    noCountriesFound: "No countries found.",
    settings: "Settings",
    selectLanguage: "Select Language",
    continue: "Continue",
  },
  zh: {
    appTitle: "2024 全球经济概览",
    poweredBy: "由 Gemini 2.5 Flash 提供支持",
    clickToExplore: "点击国家或使用列表进行探索",
    rankingsTitle: "GDP 排名",
    searchPlaceholder: "搜索国家...",
    economiesTracked: "个受测经济体",
    globalRank: "全球排名",
    gdpNominal: "GDP (名义)",
    growthRate: "增长率",
    aiInsights: "Gemini AI 洞察",
    keySectors: "关键产业",
    outlook: "2025 展望",
    analyzing: "正在分析经济数据...",
    analysisUnavailable: "暂无分析数据。",
    compareTitle: "经济对比",
    compareSubtitle: "并排分析",
    comparativeInsight: "对比洞察",
    gdpDifference: "GDP 差距",
    growthDelta: "增长差值",
    rankingGap: "排名差距",
    positions: "名",
    difference: "差距",
    larger: "更大",
    noCountriesFound: "未找到相关国家。",
    settings: "设置",
    selectLanguage: "选择语言",
    continue: "进入应用",
  },
  fr: {
    appTitle: "Économie Mondiale 2024",
    poweredBy: "Propulsé par Gemini 2.5 Flash",
    clickToExplore: "Cliquez sur un pays ou utilisez la liste",
    rankingsTitle: "Classement PIB",
    searchPlaceholder: "Rechercher un pays...",
    economiesTracked: "Économies suivies",
    globalRank: "Rang Global",
    gdpNominal: "PIB (Nominal)",
    growthRate: "Croissance",
    aiInsights: "Analyses Gemini AI",
    keySectors: "Secteurs Clés",
    outlook: "Perspectives 2025",
    analyzing: "Analyse des données...",
    analysisUnavailable: "Analyse indisponible.",
    compareTitle: "Comparaison Économique",
    compareSubtitle: "Analyse côte à côte",
    comparativeInsight: "Aperçu Comparatif",
    gdpDifference: "Différence de PIB",
    growthDelta: "Écart de Croissance",
    rankingGap: "Écart de Rang",
    positions: "positions",
    difference: "différence",
    larger: "plus grand",
    noCountriesFound: "Aucun pays trouvé.",
    settings: "Paramètres",
    selectLanguage: "Choisir la langue",
    continue: "Continuer",
  },
  ja: {
    appTitle: "2024年 世界経済",
    poweredBy: "Gemini 2.5 Flash 搭載",
    clickToExplore: "国をクリックするかリストを使用してください",
    rankingsTitle: "GDPランキング",
    searchPlaceholder: "国を検索...",
    economiesTracked: "カ国を追跡中",
    globalRank: "世界ランク",
    gdpNominal: "GDP (名目)",
    growthRate: "成長率",
    aiInsights: "Gemini AI インサイト",
    keySectors: "主要産業",
    outlook: "2025年の見通し",
    analyzing: "経済データを分析中...",
    analysisUnavailable: "分析データはありません。",
    compareTitle: "経済比較",
    compareSubtitle: "並列分析",
    comparativeInsight: "比較インサイト",
    gdpDifference: "GDP差",
    growthDelta: "成長率差",
    rankingGap: "ランク差",
    positions: "位",
    difference: "差",
    larger: "倍",
    noCountriesFound: "国が見つかりません。",
    settings: "設定",
    selectLanguage: "言語を選択",
    continue: "続ける",
  }
};
